# See https://pre-commit.ci/
ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
    exclude: ^(docs/|tests)
  - id: ruff-format

- repo: https://github.com/keewis/blackdoc
  rev: v0.4.3
  hooks:
  - id: blackdoc
    exclude: README.rst

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [--skip=*.vt*]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [tomli==2.0.1]
    files: ^src/pyminiply/.*\.py

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
    additional_dependencies: [numpy>=2.0, pytest-stub]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v21.1.2
  hooks:
  - id: clang-format

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.0
  hooks:
  - id: check-github-workflows
